// Mocks generated by Mockito 5.4.2 from annotations
// in thuprai_mvvm_test/test/auth_test/sign_up_test/service/auth_sign_up_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:thuprai_mvvm_test/screens/auth/sign_up/model/sign_in_request.dart'
    as _i6;
import 'package:thuprai_mvvm_test/screens/auth/sign_up/model/sign_in_response.dart'
    as _i2;
import 'package:thuprai_mvvm_test/screens/auth/sign_up/model/signup_request.dart'
    as _i5;
import 'package:thuprai_mvvm_test/screens/auth/sign_up/service/auth_sign_up_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignInResponse_0 extends _i1.SmartFake
    implements _i2.SignInResponse {
  _FakeSignInResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthSignUpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthSignUpService extends _i1.Mock implements _i3.AuthSignUpService {
  MockAuthSignUpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SignInResponse> signUpUser(_i5.SignUpRequest? signUpRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpUser,
          [signUpRequest],
        ),
        returnValue: _i4.Future<_i2.SignInResponse>.value(_FakeSignInResponse_0(
          this,
          Invocation.method(
            #signUpUser,
            [signUpRequest],
          ),
        )),
      ) as _i4.Future<_i2.SignInResponse>);
  @override
  _i4.Future<_i2.SignInResponse> signInUser(_i6.SignInRequest? signInRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInUser,
          [signInRequest],
        ),
        returnValue: _i4.Future<_i2.SignInResponse>.value(_FakeSignInResponse_0(
          this,
          Invocation.method(
            #signInUser,
            [signInRequest],
          ),
        )),
      ) as _i4.Future<_i2.SignInResponse>);
}
